# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jarvisui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1388, 844)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(0, 0, 1391, 841))
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap("7LP8.gif"))
        self.background.setScaledContents(True)
        self.background.setObjectName("background")
        self.loadinggif = QtWidgets.QLabel(self.centralwidget)
        self.loadinggif.setGeometry(QtCore.QRect(0, 0, 431, 201))
        self.loadinggif.setText("")
        self.loadinggif.setPixmap(QtGui.QPixmap("Jarvis_Loading_Screen.gif"))
        self.loadinggif.setScaledContents(True)
        self.loadinggif.setObjectName("loadinggif")
        self.circledesign = QtWidgets.QLabel(self.centralwidget)
        self.circledesign.setGeometry(QtCore.QRect(40, 250, 201, 201))
        self.circledesign.setText("")
        self.circledesign.setPixmap(QtGui.QPixmap("pngegg.png"))
        self.circledesign.setScaledContents(True)
        self.circledesign.setObjectName("circledesign")
        self.JARVIS = QtWidgets.QLabel(self.centralwidget)
        self.JARVIS.setGeometry(QtCore.QRect(610, 10, 221, 111))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.JARVIS.setFont(font)
        self.JARVIS.setStyleSheet("color: rgb(255, 255, 255);\n"
"background:transparent;\n"
"border-radius:none;")
        self.JARVIS.setObjectName("JARVIS")
        self.buttondesign = QtWidgets.QLabel(self.centralwidget)
        self.buttondesign.setGeometry(QtCore.QRect(940, 480, 201, 201))
        self.buttondesign.setText("")
        self.buttondesign.setPixmap(QtGui.QPixmap("clipart4609831.png"))
        self.buttondesign.setScaledContents(True)
        self.buttondesign.setObjectName("buttondesign")
        self.buttondesign_2 = QtWidgets.QLabel(self.centralwidget)
        self.buttondesign_2.setGeometry(QtCore.QRect(1160, 480, 201, 201))
        self.buttondesign_2.setText("")
        self.buttondesign_2.setPixmap(QtGui.QPixmap("clipart4609831.png"))
        self.buttondesign_2.setScaledContents(True)
        self.buttondesign_2.setObjectName("buttondesign_2")
        self.runbutton = QtWidgets.QPushButton(self.centralwidget)
        self.runbutton.setGeometry(QtCore.QRect(1000, 560, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.runbutton.setFont(font)
        self.runbutton.setStyleSheet("color: rgb(255, 255, 255);\n"
"background:transparent;\n"
"border-radius:none;")
        self.runbutton.setObjectName("runbutton")
        self.exitbutton = QtWidgets.QPushButton(self.centralwidget)
        self.exitbutton.setGeometry(QtCore.QRect(1220, 550, 81, 61))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.exitbutton.setFont(font)
        self.exitbutton.setStyleSheet("color: rgb(255, 255, 255);\n"
"background:transparent;\n"
"border-radius:none;")
        self.exitbutton.setObjectName("exitbutton")
        self.design = QtWidgets.QLabel(self.centralwidget)
        self.design.setGeometry(QtCore.QRect(1040, 40, 271, 151))
        self.design.setText("")
        self.design.setPixmap(QtGui.QPixmap("PinClipart.com_technology-borders-clip-art_4014880.png"))
        self.design.setScaledContents(True)
        self.design.setObjectName("design")
        self.time = QtWidgets.QTextBrowser(self.centralwidget)
        self.time.setGeometry(QtCore.QRect(1100, 70, 191, 51))
        self.time.setStyleSheet("background:transparent;\n"
"border-radius:none;\n"
"color:white;\n"
"font-size:30px;")
        self.time.setObjectName("time")
        self.date = QtWidgets.QTextBrowser(self.centralwidget)
        self.date.setGeometry(QtCore.QRect(1110, 120, 191, 51))
        self.date.setStyleSheet("background:transparent;\n"
"border-radius:none;\n"
"color:white;\n"
"font-size:30px;")
        self.date.setObjectName("date")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.JARVIS.setText(_translate("MainWindow", "JARVIS"))
        self.runbutton.setText(_translate("MainWindow", "Run"))
        self.exitbutton.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
